cabal-version:      3.0
name:               turing-sim
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Brage Isak Keiseraas
maintainer:         bikeiser@uio.no
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

executable turing-sim
    import:           warnings
    main-is:          Main.hs
    other-modules:
        Parser
        , Turing
    build-depends:
        base ^>=4.18.3.0
        , parsec
        , optparse-applicative
    hs-source-dirs:   exe
    default-language: Haskell2010

